### PR TITLE
[radio@driglu4it] Menu and icon improvements - Fixes #2843

### LINKED ISSUE #2843: radio icon
radio icon

```
 *  Radio Icon applet / Updated on 2019-11-29 18:02:10    
 * cinnamon 19.3  4.4.8
 *  linux mint kernel 5.3.0.28-generic
 * rx 580 radeon amd/ati ellesmere pulse sapphire
* Intel core I7 K875 overclock 2.93ghz x4 
* mem corsair 16.0 gb 
* Hard drives 3394.5 GB samsung rpm 5400
   
 

<!-- Author list: https://github.com/linuxmint/cinnamon-spices-applets/blob/master/.github
      radio@driglu4it //// 
   **Notify author of applet**
       Driglu4it 

**Issue**
just want to ask a question its not really a issue but how do i change the icon thats on the radio.
take a screen shot of the icon on the top right corner. am sorry for asking for help but there somethings need to know about linux.lol



**Steps to reproduce**
*


**Expected behaviour**

*

**Other information**
*
![Screenshot from 2020-02-02 23-07-46](https://user-images.githubusercontent.com/60449271/73616912-f9a54380-4610-11ea-9a9f-94fdf2e85e5f.png)

### PR DESCRIPTION
**Pull request by claudiux**
~~Work in progress.~~
This PR fixes #2843.

### CODE REVIEW

File: radio@driglu4it/files/radio@driglu4it/applet.js [hunk 1]
```diff
@@ -26,7 +31,12 @@ MyApplet.prototype = {
   _init: function(orientation, panel_height, instance_id) {
     Util.spawnCommandLine("mocp");
     Applet.TextIconApplet.prototype._init.call(this, orientation, panel_height, instance_id);
-    this.set_applet_icon_symbolic_path(GLib.get_home_dir() + "/.local/share/cinnamon/applets/" + UUID + "/icons/radio.svg");
+
+    Gtk.IconTheme.get_default().append_search_path(ICONS_DIR);
```
Comment (Odyseus) [inline radio@driglu4it/files/radio@driglu4it/applet.js]: Hello, @claudiux.

I know that this PR is a work in progress, but I have to point out one thing.

This call to `Gtk.IconTheme.get_default().append_search_path()` is not needed. It is already done automatically for all xlets types [since Cinnamon 2.0.x](https://github.com/linuxmint/cinnamon/commit/db4ade8188581f2c46991aaa70757235c406cb8f).

Comment (Padre2) [reply radio@driglu4it/files/radio@driglu4it/applet.js]: @claudiux  @Odyseus 
  Is it not sufficient just to remove the line:
`this.set_applet_icon_name('radio');`
This allows the SVG icon to display.

Comment (Padre2) [reply radio@driglu4it/files/radio@driglu4it/applet.js]: @claudiux  @Odyseus 
  Is it not sufficient just to remove the line:
`this.set_applet_icon_name('radio');`
This allows the SVG icon to display.

Comment (claudiux) [reply radio@driglu4it/files/radio@driglu4it/applet.js]: Hello, @Odyseus. It is fixed, now. Thank you.

Comment (claudiux) [reply radio@driglu4it/files/radio@driglu4it/applet.js]: Thank you for your reviews.

**Comment by brownsr** [comment]
ping @Driglu4it

**Comment by brownsr** [comment]
No response from author, treated as bugfix, merging
