### PR TITLE
Resolve VBox version and issue new startvm command

### LINKED ISSUE #2168: vboxlauncher@mockturtl: VBox 6 --startvm change breaks VM startup
```
 * Version: 0.4.0
 * Cinnamon version: 4.0.8
 * Distribution: Mint 19.1
 ```

@mockturtl 

It appears VBox have overhauled their command line utilities and moved --startvm to a different command.

**Steps to reproduce**
* Replace v5 VirtualBox install with v6
* Attempt to start a VM from the launcher

Result: "--startvm is an option for the VirtualBox VM runner (VirtualBoxVM) application, not the VirtualBox Manager."

**Expected behaviour**
VM Should start

### PR DESCRIPTION
**Pull request by Centurix**
VirtualBox changed their command line startup for VM images.
* Checks vbox major version
* Issues updated vboxmanage command for V6 and older --startvm for < V5

Fixes #2168 

@mockturtl 
@mhosse

### CODE REVIEW

File: vboxlauncher@mockturtl/files/vboxlauncher@mockturtl/applet.js [hunk 1]
```diff
@@ -230,7 +239,11 @@ MyApplet.prototype = {
   }
   
 ,  startVboxImage: function(id) {
-    Util.spawnCommandLine(CMD_VBOX_VM + id)
+    if (this.vboxMajorVersion() >= 6) {
```
Comment (mockturtl) [inline vboxlauncher@mockturtl/files/vboxlauncher@mockturtl/applet.js]:
```suggestion
    let cmd = this.vboxMajorVersion() >= 6 ? CMD_VBOX6_VM : CMD_VBOX_VM
    Util.spawnCommandLine(cmd + id)
```

**Comment by mockturtl** [comment]
@Centurix Thanks!
